[package]
name = "yacurses"
description = "Yet Another Curses library."
repository = "https://github.com/Lokathor/yacurses"
version = "0.0.1-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
chlorine = "1"
